site_name: onebuilding-scraper
repo_url: https://github.com/szvsw/onebuilding-scraper
site_url: https://szvsw.github.io/onebuilding-scraper
site_description: This is a repository for scraping data from climate.onebuilding.org.
site_author: Sam Wolk
edit_uri: edit/main/docs/
repo_name: szvsw/onebuilding-scraper
copyright: Maintained by <a href="https://szvsw.com">Florian</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append('../')
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/szvsw/onebuilding-scraper
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/onebuilding-scraper

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
